---
- name: Deploy Docker Image to Kubernetes
  hosts: localhost
  connection: local
  tasks:
    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        state: present
        src: ../k8s/deployment.yaml

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        state: present
        src: ../k8s/service.yaml